[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
streaming_payroll_solana = "99Dw4hJctWvd3j82DjFFNr9FNQZ3319SoXdw9Wb2MhRG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet/ProgramAuthority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
