[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
streaming_payroll_solana = "AQgEzkKH5QkFYfG7kMXnnNwJEtKcaaimhCQUSW4MvDAD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tusharmac/imp/Projects/Solana/testing_wallets/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
